### PR TITLE
Update src/DOM.js

### PR DESCRIPTION
**Pull request by BlackScorp**
Dont Create new DOM element if its already exists

toggleComponent("DOM") creates new DOM element instead of Editing the existing ones

### CODE REVIEW

**Comment by sorenbs** [comment]
Would this allow for a situation where an entity is being associated with a dom element that has some old css styles that does not apply to the new entity?

**Comment by BlackScorp** [comment]
uhm i actually dont know what you mean, can you explain more please?

**Comment by sorenbs** [comment]
I just thought that when reusing dom elements, they might have some old css properties. For example, if you create a dom entity with a sprite, removes the dom component, removes the sprite and adds the dom component again the dom element would still have the background image set.
I haven't tested if that is a real problem or just something i'm making up though :-)

**Comment by BlackScorp** [comment]
hm.. that could be, in this case Crafty components need an uninitial event or function which is called on removing the component, then removing the DOM object completly on removing DOM component would allow to swich DOM to Canvas in runtime.

what do you think? add an destructor to core.js in removeComponent function then we can add uninit functions to canvas and dom and stuff

**Comment by sorenbs** [comment]
Yeah, i think adding an uninit function to components would be a neat general solution.

**Comment by sorenbs** [comment]
Okay, i have added the uninit call and corresponding function in DOM. From my brief testing this enables the DOM/Canvas switching. Pretty cool.

https://github.com/louisstow/Crafty/commit/bcc789c30467049f9073a38834084e486730e826

**Comment by BlackScorp** [comment]
can you post a jsfiddle link? i want to see it :D

**Comment by sorenbs** [comment]
hah :-)

The autogenerated snapshot does not pickup changes in the develop branch. We will have to find a solution for that to make it feasible to use jsfiddle again.

**Pull request closed without merging**
