### PR TITLE
Remove old build system

### PR DESCRIPTION
**Pull request by potomak**
This PR removes old PHP build system and API documentation generation. It removes also a lot of static assets (css, images) hosted at https://github.com/craftyjs/craftyjs.github.com.

If merged the [build page](https://github.com/craftyjs/Crafty/wiki/Building) should also be changed.

See also bc7ce76

### CODE REVIEW

**Comment by starwed** [comment]
Just to be clear, the static assets aren't used anywhere in the actual API docs, right?

**Comment by kevinsimper** [comment]
As @starwed says, i do not think that all of the assets should be deleted. Mainly because it should be possible to create the documentation on your own computer.

**Comment by potomak** [comment]
I removed images as they are present at https://github.com/craftyjs/craftyjs.github.com/tree/master/images

The current workflow is:
1. generate api documentation
2. move generated docs to https://github.com/craftyjs/craftyjs.github.com

I'm trying to find a better way to make api documentation readable also from outside of the site repo, it should be also a solution for #534.

**Comment by kevinsimper** [comment]
I will go ahead an merge this, because as @potomak point out is the workflow like that now.

But you should be able to build the documentation offline, but that would need to be built from the start, so it is fine to remove the old one now.

**Comment by starwed** [comment]
This did delete some resources needed for building local documentation; most importantly `global.css`, but also a couple images used in the header and footer.

**Pull request merged**
