### PR TITLE
Server build - split browser & display context from rest of code

### PR DESCRIPTION
**Pull request by mucaho**
A first attempt to split them, mainly using the philosophy from [this document](https://github.com/mucaho/npm_crafty/tree/master/diff#removed-from-crafty);
-  ~~src files have their name appended with "_server" if they represent backend code.~~
- some files have been split in 2 parts, if a chunk of code didn't fit into either worlds:  
  *\*  ~~`extensions` into `extension` and `extensions_server` (has only Crafty.keys and Crafty.mouseButtons)~~  
  *\*  ~~`controls` into `input` and `controls_server` (has only Multiway, Twoway, Fourway)~~  
  *\*  ~~`animation` has had it's `SpriteAnimation` component removed and put into `sprite`~~  
  *\*  ~~`drawing` has had `Crafty.scene` & `zeroFill` removed and they were put into `scene_server`~~  
  **The specific have changed; see later posts!**
- dummy objects have been added (like `window`, `Crafty.viewport`, etc) before & after definition of crafty server build

The old build functionality is intact: all tests pass & api build works.

You can build the server version with `grunt server` (as you guessed only the **_server** files get included in the server build). Of course only some qunit tests pass at the moment.
You can run a simple example with `node test_server.js`.
There is much room for improvement: 
- first of all changing the code so that the backend code does not have to be included. (e.g. instead of calling a method directly on `Crafty.viewport`, we could trigger events that `Crafty.viewport` listens to)
- as much of the functionality has been omitted, extensive testing & special qunit tests are needed

Is this the correct approach? The more PRs get merged into develop branch, the harder it will be to merge something like this if we plan to.

### CODE REVIEW

**Comment by mucaho** [comment]
see also #578 #440

**Comment by starwed** [comment]
I think I'd prefer to do this in smaller steps.  For instance, lets do things like fixing calls to viewport _before_ we try to reorganize the code base.

We should think long and hard about the way to proceed; let's punt on this sort of large change until after the next release, which should actually be pretty soon.

Nice work in identifying the problem areas, though!

**Comment by mucaho** [comment]
Ok, but remember this is just moving of code into different files. No "changes" to the code itself.
EDIT:
My point being that if we want to support backend-only code, then the code should be reorganized slowly into appropriate files (the sooner the better imo). It won't change anything to the normal crafty release, while we can take our time and tune the backend build in the background, without worrying to retrofit ongoing changes to the development branch.

**Comment by mucaho** [comment]
On the other hand I'm certain there is a better way to reorganize the files.

**Comment by mucaho** [comment]
I have given some more thought about how to better reorganize the files:
- put all **src** files into three folders (**src/common, src/backend, src/frontend**) using the `git mv` command which makes the changes more transparent
- split & create the **new src files** out of the old ones:
- [x] frontend/drawing.js - scene -> backend/scene.js  
- [x] frontend/controls.js - Multiway, Twoway, Fourway -> backend/controls.js  
- [x] common/animation.js - SpriteAnimation -> frontend/sprite.js  
- [x] frontend/extensions.js - zeroFill -> common/2D.js  
- [x] frontend/extensions.js - keys, mouseButtons -> common/keycodes.js  
- add the **backend setup** specific files
- update the paths in `require(core.js)` statements, in the **grunt build** file and in the **package.json** file

**Comment by mucaho** [comment]
inspired by #763 :

I like the playgrounds very much, but on the other hand the playgrounds and any other _frontend_ functionality (`Color`, ...) won't work if Crafty's codebase is going to be split into _frontend(browser) and backend(node)_ #603 . The plan (for now) is to omit _frontend_ functionality from the _backend_ code & tests. The _backend_ code is almost ready, but many of the tests (that will be in the _backend_) have some kind of _frontend_ functionality (mostly `Color` components). Does anyone know an elegent way to deal with this?

**Comment by mucaho** [comment]
I recently discovered [node-localstorage](https://www.npmjs.com/package/node-localstorage) which acts as a drop-in replacement for the browser `localStorage`.

``` javascript
if (typeof localStorage === "undefined" || localStorage === null) {
  var LocalStorage = require('node-localstorage').LocalStorage;
  localStorage = new LocalStorage('./scratch');
}
```

[Grunt node-qunit](https://www.npmjs.com/package/grunt-node-qunit) can be used to run the tests in a `node` environment, instead of the `phantomjs` environment provided by `grunt-contrib-qunit`.

**Comment by mucaho** [comment]
Superseded by #902, closing.

**Pull request closed without merging**
