### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dobnarr**
Fix for Twoway jump bug.

### CODE REVIEW

**Comment by mpetrovic** [comment]
lot of extra commits in there. Mind cleaning it up?

**Comment by dobnarr** [comment]
Sorry, I screwed up - I think I was supposed to submit the pull request to the dev branch, not the master.  Very new at this.  I only changed 2 lines from the dev source

**Comment by dobnarr** [comment]
Is it possible to delete this pull request and do it right?

**Comment by mpetrovic** [comment]
its for the right branch, but there are just a lot of commits that aren't yours. I'll close it and you can try again.

**Comment by dobnarr** [comment]
Thanks for closing it - what should I do differently?  I was following directions from here: 
https://groups.google.com/forum/?fromgroups=#!topic/craftyjs/geUU8qnucTQ

**Comment by sbyrnes321** [comment]
"Choose the option to submit from your "develop" branch to the craftyjs/Crafty "develop" branch." You got the "from" part correct, but missed the "to" part. This is in the Pull Request dialog box. Again, before you finally submit the pull request, you should click the tabs in the dialog box to double-check what you're submitting. Should be just one commit if that's what you did. :-D

**Pull request closed without merging**
