### PR TITLE
Tiny change to add the ID property to every entity

### PR DESCRIPTION
**Pull request by mucaho**
I have searched the code, there is no apparent way to uniquely identify the entity (unless you extract the id from _entityName or i missed something).

### CODE REVIEW

**Comment by sbyrnes321** [comment]
Actually it is already possible: `some_entity[0]` is its ID.

http://craftyjs.com/api/Crafty.html

If you could tell us the places where you looked (in vain) for that information, it might be helpful for improving the documentation.

Actually, I'm in favor of this pull request and I hope it's accepted, notwithstanding the fact that it's redundant. The reason is, writing `this._id` in your code is much more readable and intuitive than writing `this[0]`.

**Comment by mucaho** [comment]
Ah thanks. I skimmed through that part too quickly. I have seen alot of `this[0]` throughout the source code wondering what that specific property at that index might be.

I don't think that having the redundancy would be good. The "better" alternative would be to refactor all `this[0]` to `this.ID`.

**Comment by mucaho** [comment]
On the other hand refactoring may break existing code :(

**Comment by mucaho** [comment]
What about a wrapper getter method like Crafty Core.has(componentID)? 
That would not break existing code, the property would not be rendundant and most importantly, it would be **better readable**.

``` javascript
/**@
* #.getId
* @comp Crafty Core
* @sign public Number .getId(void)
* Returns the ID of this entity.
*
* For better performance, simply use the this[0] property.
*/
getId: function () {
    return this[0];
},
```

**Comment by starwed** [comment]
Out of curiosity, I checked whether there'd be any performance penalty for using e.id instead of e[0].  [Here is the jsperf link](http://jsperf.com/index-vs-property).  I don't see any real difference in FF or Chrome, so probably no concern there.

A wrapper might make sense, though again, we'd want to make sure there's no performance issues.  Is using a getter faster than calling a function?

_e:_ Actually, the ID is one of the few properties that should never, ever change, right?  Maybe it could just be duplicated at entity creation.

**Comment by mucaho** [comment]
This site is awesome! Thanks for sharing :+1: 
- **Is using a getter faster than calling a function?**
  I created a test comparing the use of a simple `function` vs a `__defineGetter__`. [jsperf link](http://jsperf.com/index-vs-property/2). I ran it on FF19, it was minor win for function. I ran it on chrome it was a bit faster with getter.
  Should i rewrite the code to use `__defineGetter__` instead ? (and the `defineProperty` / normal `function` fallback for browsers that do not support this). How often will `getId()` be called anyway? - existing code uses `this[0]` anyway.
- **Actually, the ID is one of the few properties that should never, ever change, right?**
  AFAIK, id is a simple `Number` thus it is copied by value when returned by a getter method. The user can do with it what he wants, as long as he does not modify `this[0]` directly.

**Comment by starwed** [comment]
I think I'd prefer to just copy the ID into an `.ID` propery on entity creation.  Can anyone see anything wrong with this?  As far as I know the ID will never change, so we don't need to worry about keeping them in sync.

**Comment by mucaho** [comment]
Whats the advantage of having another property over returning it with the help of a function?

**Comment by starwed** [comment]
> Whats the advantage of having another property over returning it with the help of a function?

Just brevity.  After letting the idea simmer for a while, I think a function call is probably less confusing.  So I'll go ahead and merge this as is.

**Pull request merged**
