### PR TITLE
Documentation fixes and code formating

### PR DESCRIPTION
**Pull request by ahilles107**
If any one coud review this will be very cool. 

this PR add to docs:
- more viewport functions (zoom, pan, follow ...)
- HitBox component in collision
- Delay component

and more...

Docs must receive more work, specially in the formatting and appearance.

### CODE REVIEW

**Comment by ahilles107** [comment]
@sorenbs - i want merge this before new version, can you find a moment for review, and build new api for craftyjs.com after release?

**Comment by BlackScorp** [comment]
Looks good for me, didnt found anything bad

**Comment by sorenbs** [comment]
Sure. I will merge this before i create the release tomorrow evening.

**Comment by sorenbs** [comment]
Very nice work on the documentation!

You appear to have something fancy going on with your indentation. One example: https://github.com/ahilles107/Crafty/blob/e9725062f53f4782a42ea38f713cf0be7333a52e/src/HashMap.js

**Comment by ahilles107** [comment]
Yep, i must correct my settings on sublime text.

**Comment by ahilles107** [comment]
@sorenbs can you update docs on craftyjs.com?

**Comment by sorenbs** [comment]
louisstow is on it.

**Comment by ahilles107** [comment]
@louisstow Can you add changes from build/global.css to craftyjs.com? Especially for "pre code".

**Pull request merged**
