### PR TITLE
Fix image loader on IE; add loader test

### PR DESCRIPTION
**Pull request by potomak**
`obj.src = ""` triggers the error event on IE while it doesn't on webkit
so adding a check for the type of browser fixes the error.

See #549 for more details.

### CODE REVIEW

**Comment by kevinsimper** [comment]
Looks good :+1: 

Really cool that you found the solution for the problem!

**Comment by starwed** [comment]
The webkit workaround is discussed in #382.  The original bug in webkit is [7731](http://code.google.com/p/chromium/issues/detail?id=7731).

There might also be a better way around it; the webkit bug only occurs when you try to load an already loaded image, so perhaps we could directly detect that.

**Comment by kevinsimper** [comment]
@starwed How do you think that best could be done? Should there be stored a list of already downloaded files in array?

**Comment by potomak** [comment]
@starwed @kevinsimper I think we could merge this PR to make it work now and open a new issue about that to resolve it in a better way in the future.

Moreover this is a **workaround** to mitigate a webkit bug, so it should be solved _as a workaround_.

Note: this bug is hanging since **11 months** ago, this means that either very few people are using IE or very few people are using Crafty to develop HTML5 games.

**Comment by kevinsimper** [comment]
@potomak I will merge this then. Will you open that new issue?

**Pull request merged**
