### PR TITLE
crafty-local should read file-list from package.json

### PR DESCRIPTION
**Pull request by sbyrnes321**
(maintaining separate file-lists is prone to errors when the file list is updated.)

### CODE REVIEW

**Comment by mpetrovic** [comment]
does (function () {}()) work? If so, do you need the outermost parens?

**Comment by sbyrnes321** [comment]
Yes it works - I tested in firefox and chrome at least. I switched the order because jslint told me to, I didn't think it through too carefully. I found a discussion at

http://benalman.com/news/2010/11/immediately-invoked-function-expression/

which suggests that both of them work equally well, so it seems to me that jslint (Crockford) has an arbitrary preference. Oh well, whatever.

As for the outermost parentheses, the blog says they're required to avoid a syntax error.

**Comment by starwed** [comment]
What is the correct way to test this?  

Any use of `crafty-local` always gives the permission error for me -- unless I spin up a local server.  Is this the intended use?  (I remember having problem with Chrome accessing the local file system, but Firefox always seemed willing.)

**Comment by mpetrovic** [comment]
Yes, it's the intended use.

I run it with the file:// and turn off strict-origin-for-file-uris, or
whatever, in firefox when doing core work. If you can install a web server
locally and run it from there as well, but I don't want a web server on the
same machine I game on.

**Comment by sbyrnes321** [comment]
I tested by running core.html. Actually if you open `core.html` you'll see the instructions for using crafty-local. Maybe I should copy them here too...

It works in chrome if you open chrome with the flag `--allow-file-access-from-files`.

It works in firefox if crafty-local is in the same directory or a subdirectory as the HTML file calling it. But not if it's in a parent directory, cousin directory, etc. [Unless you change a setting in about:config, `security.fileuri.strict_origin_policy` --> false.]

I don't know about other browsers.

**Comment by starwed** [comment]
Ok, looks good to me.  (I just tested with `python -m SimpleHTTPServer 8080`).

The error message should probably mention the intended usage, but I'm not too worried about that.

**Comment by mpetrovic** [comment]
The intended usage is for us. No one not doing work on the engine itself
should be using Crafty-local.js.

**Pull request merged**
