### PR TITLE
Support for other repositories

### PR DESCRIPTION
**Pull request by ahilles107**
Hi, im back ;)
I do this today. CraftyComponents.com will supported this change today.

### CODE REVIEW

**Comment by sorenbs** [comment]
While i agree it should be easy to use an alternative repository i think we should keep crafty-modules.com as the default to use if no repository is specified.

crafty-modules.com is open source, open for commiters and intended to be as much a community effort as crafty itself. 

The way i see it, the place where support for alternative repositories can be a great benefit is if you are developing your game as closed source and want to keep all sources on your internal network.

I suppose we allow the following two ways of using Crafty.modules:

Crafty.modules("http://craftycomponents.com", { moveto: 'DEV' }, function () {
    //module is ready
    Crafty.e("MoveTo, 2D, DOM");
});

Crafty.modules({ moveto: 'DEV' }, function () {
    //module is ready
    Crafty.e("MoveTo, 2D, DOM");
});

**Comment by ahilles107** [comment]
Sorry for second commit ;/ it's change nothing.

With crafty-modules.com is one main problem - not many people know scala ;/

CraftyComponents.com is writen in PHP (on Symfony2 (https://github.com/symfony/symfony), Twig (https://github.com/fabpot/Twig), and Doctrine (https://github.com/doctrine/doctrine2)) - its biggest comunity on github. 

CraftyComponents.com will be open sorce to. (i must create repo on github, and clear parameters.ini). I and others from FlyWithMonkey have a lot ideas for this page (ex. comments for components, contributors rankings etc.). And in scala we canot help ;/

Then why don't choose CraftyComponents.com (I know - it was a lot of code, but in our side too).

**Comment by ahilles107** [comment]
https://github.com/ahilles107/CraftyComponents - CraftyComponents is open source now. Tomorrow i will write docs for instalation.

**Comment by sorenbs** [comment]
If you and your company want to commit to supporting craftycomponents.com i think we should let that be the default. It's been 5 years since i have done any php, so it should be interesting to read through the code and see what has changed since then.

We would like to release a new version of Crafty soonish, and i would like the module system to be fully operational first. How much time do you think you need?

I have one feature request also: always lowercase the filenames, so http://cdn.craftycomponents.com/MoveTo-1.8.js -> http://cdn.craftycomponents.com/moveto-1.8.js

**Comment by ahilles107** [comment]
Nice to hear this.

Time depends on the number of features. For now we want add cron for updating components one time each day, comments for components and added jsfiddle examples on component page. We also want to start work on Crafty Game Boilerplate - but it's not exactly related with craftycomponents.com

for now it should work for moveTo. Now I working with github parser for load crafty.js (paths in package.json files object)

**Comment by sorenbs** [comment]
It would be nice if you could support github post-receive hooks to have components updated instantly. That produces a much better workflow when discussing and showing changes to somebody.

You should also consider serving the js files from something like s3 to get higher availability. As you are using a subdomain this can always be changed later.

**Comment by ahilles107** [comment]
We can support post-recive hooks. We use rackspace nad we can create cdn on it.

**Comment by sorenbs** [comment]
Sounds good!

Venlig Hilsen
Søren

2012/1/10 Paweł Mikołajczuk <
reply@reply.github.com

**Comment by sorenbs** [comment]
You could consider using http://disqus.com/ for comments.

**Comment by sorenbs** [comment]
When i try to update at
http://craftycomponents.com/components/single/8/crafty i get a 503 server
error.

Venlig Hilsen
Søren

**Pull request merged**
