### PR TITLE
Streamline Twoway input handling

### PR DESCRIPTION
**Pull request by mucaho**
Instead of polling the current keyboard state, use keyboard event data

### CODE REVIEW

**Comment by starwed** [comment]
Looks good.  Same deal as the other PR, though -- could you squash down to one commit?

If you're unsure how, let me know what system you're using and I can point you in the right direction!  :)

**Comment by starwed** [comment]
No need to close the pull request -- you can rebase and force push to your repo if you want.

**Comment by mucaho** [comment]
starwed i have been trying to get github for windows working in the last hour, i just don't have the nerves for it, i will open new PRs

**Comment by starwed** [comment]
Ok, no worries.  :)  I tend to work at the commandline, so not sure how their client works.

**Pull request closed without merging**
