### PR TITLE
fix to issue #761

### PR DESCRIPTION
**Pull request by heniotierra**
Small fix for bug that occurs in very specific situations in Delay component, issue https://github.com/craftyjs/Crafty/issues/761

### CODE REVIEW

**Comment by heniotierra** [comment]
@mucaho Sorry, seems like I didn't merge your last modifications. Will try to fix that.

**Comment by heniotierra** [comment]
I think this is it.

**Comment by heniotierra** [comment]
Please, look at the last comment there.

**Comment by mucaho** [comment]
Thanks for this PR! I still don't fully understand the bug though. `index`, `splice` and `push` _should_ play along together (even when nesting them inside each other in loops).

**Comment by mucaho** [comment]
Yeah, the problem was that inside the EnterFrame loop (which operates on decreasing index), the array could have been shrunk even further by a callback that internally invokes the `cancelDelay` method (which shrinks the array with `splice`). The results is incorrect iteration in the EnterFrame loop.

The natural way would be to queue up delays to be deleted in a seperate array, which will then be processed at the end of the loop. This PR does it even better, by using the already existing array to invalidate entries, thus saving performance.

The code does a get a bit more complicated, but this is the best way to deal with "concurrent modifications" on an array (unless we figure out a better way to do this).

**Comment by mucaho** [comment]
I searched for an easier, not so intrusive approach and I found one. It's essentially the same as yours, you can just remove the item at the start of the next "EnterFrame" instead of removing it at the end of the current frame (thus saving one extra loop).

``` diff
diff --git a/src/time.js b/src/time.js
index 02a6acb..e9544bf 100644
--- a/src/time.js
+++ b/src/time.js
@@ -13,7 +13,9 @@ Crafty.c("Delay", {
             var index = this._delays.length;
             while (--index >= 0) {
                 var item = this._delays[index];
-                if (item.start + item.delay + item.pause < now) {
+                if (item === false) {
+                    this._delays.splice(index, 1);
+                } else if (item.start + item.delay + item.pause < now) {
                     item.callback.call(this);
                     if (item.repeat > 0) {
                         // reschedule item
@@ -125,7 +127,7 @@ Crafty.c("Delay", {
         while (--index >= 0) {
             var item = this._delays[index];
             if(item.callback == callback) {
-                this._delays.splice(index, 1);
+                this._delays[index] = false;
             }
         }

```

The [new JSFiddle](http://jsfiddle.net/Dj48n/17/) works for me with this code.

**Comment by heniotierra** [comment]
Nice! :) I'll update the PR with these changes. Thanks!

**Comment by heniotierra** [comment]
But wait, correct me if I'm wrong. Did you put 2 (two) <i>.splice</i>'s in the loop? One at line 17 and another at line 28? The first one(line 17) for canceled delays only, right? That works marvels!
I did just update the PR.

**Comment by mucaho** [comment]
Awesome, with combined effort we managed to tackle this issue :)

Since this commit is linked to the previous, merged commits for the "Delay" component, I'm going ahead and merging this.

**Comment by heniotierra** [comment]
Really awesome! :dancers:

**Pull request merged**
