### PR TITLE
Attempt to fix error with Crafty.frame()

### PR DESCRIPTION
**Pull request by highwaycoder**
Was returning undefined, should now return the frame number as expected.  Untested though.

### CODE REVIEW

**Comment by highwaycoder** [comment]
Needs to be tested before it's merged, I'm moving on to other things in the mean time.

**Comment by kevinsimper** [comment]
Thanks for the PR. 

Where was it undefined? Code? By moving a variable could indicate you are asking for the frame number before Crafty has started. 

Also you should check the code by running grunt check. You can see how in the Contribute file.

**Comment by highwaycoder** [comment]
http://jsfiddle.net/pnZN7/

Demonstrates the problem quite nicely, I think.  I'm assuming by the time an EnterFrame event occurs, Crafty is definitely running, yes?

I haven't got a local WC of this repo at the moment and I have a fair amount on my plate right now so it'll be a while before I can test this fix myself (doesn't occur to me to be worth much effort given how you can get the frame count from the EnterFrame event anyway).  If my schedule calms down and nobody's fixed this or tested my fix, I'll put some more effort into it at that point.

**Comment by kevinsimper** [comment]
Submitted a patch for this at #689

**Comment by highwaycoder** [comment]
I'll close this PR then.

**Pull request closed without merging**
