### PR TITLE
Use system objects instead of hardcoded references for graphics layers

### PR DESCRIPTION
**Pull request by starwed**
Currently references to the canvas/dom/webgl graphics layers have to be hardcoded in some places.

This PR takes the current layer objects and defines them as systems using `Crafty.s`.  This means
- Events can be bound directly to the graphics layer, instead of going through global Crafty events
- Cleanup can be done by each layer when the system is destroyed
- The layers can now be recreated anew every time `Crafty.init()` is called

The new design should more easily allow for multiple layers of each type in a future PR, although there's an additional issue that has to be resolved first.  (Refactoring how entities attach themselves to a particular graphics layer so that it's easier to add/remove them.)

_e:_ I should add that I tested that all types of components still rendered with these changes.

### CODE REVIEW

**Comment by mucaho** [comment]
Pretty big change, highlighting the significance of visual regression tests (#950) :)
How do users access [`Crafty.canvasLayer`](http://craftyjs.com/api/Crafty-canvasLayer.html) methods (and of other layers) after this change?
Would you kindly explain what the purpose of the last commit is? Aren't systems unique and initialized from scratch once destroyed or are there properties still available after destroying system?

**Comment by starwed** [comment]
>  Is the WebGL div somewhere located in the DOM tree so we can document that?

I believe it's mentioned in the docs for WebGL, but we probably just want to add a section in the non-api documentation that discusses layers.  Since my immediate goal is to completely change how they work, I feel like it'd be best to hold-off on improving the documentation until all the changes have gone through.

> After you destroy systems, do they get reinitialized when requested again?

Currently no, you'd have to explicitly declare them again.  For built-in systems like the ones this PR adds, it becomes Crafty's responsibility to redeclare them when you call `Crafty.init()`.

> Would you kindly explain what the purpose of the last commit is? Aren't systems unique and initialized from scratch once destroyed or are there properties still available after destroying system?

It's the same "shared object" problem mentioned in the [docs for components](http://craftyjs.com/documentation/components.html) -- if you instantiate two systems from the same base object, and that base object has an array or object defined on it, then it'll be shared by both systems.  The immediate issue was actually destroying/recreating a system using stop/init, but it would also matter in the future when you might create multiple layers of the same type.

**Comment by mucaho** [comment]
Ok, feel free to merge when ready.

**Comment by starwed** [comment]
Merging this in.

**Pull request merged**
