### PR TITLE
Pause audio by id

### PR DESCRIPTION
**Pull request by jmwohl**
Added ability to pause/unpause/togglePause of individual audio objects.  Useful for pausing music during a 'pause screen' without pausing other sounds, among other things.

### CODE REVIEW

**Comment by mpetrovic** [comment]
Um, can you remake this but only with your own commits in it?

**Comment by jmwohl** [comment]
Whoops.  Yeah... is it because all of these commits were in the develop branch already?

**Comment by jmwohl** [comment]
Sorry about this... Should I make the pull request to the develop branch of craftyjs/Crafty?

**Comment by mpetrovic** [comment]
Looks like if you merge in commits to your branch than do the pull request,
it'll throw them in there.

I think your best bet is to go back in the tree to when you split it,
cherry-pick your commits into it, then PR that.

**Comment by jmwohl** [comment]
Hmm... I only forked it a few days back though, long after the extraneous commits were made.  I think the issue is that I submitted the pull request to the master branch, and all of those other commits are already merged into develop but not into master.

If I submit the pull request to the develop branch instead of master, only my commits appear.  I'm going to try that — feel free to reject those last two PRs to the master branch.

Jon

---

(608) 772-9645

**Pull request closed without merging**
