### PR TITLE
Improve attr documentation

### LINKED ISSUE #738: Update .attr docs
Right now the docs for `.attr` does not say anything about that you can also use it to get values.

But it should say that you should use the direct way instead.

```
this.attr('name', 'Hero');
this.attr('name'); // Hero
```

Somebody in the forum was confused about it:
https://groups.google.com/forum/#!topic/craftyjs/ChukZ7SvG40

### PR DESCRIPTION
**Pull request by mucaho**
This commit fixes #738, it also adds new signatures and more
detailed explanation to the inner workings of attr.

### CODE REVIEW

**Comment by kevinsimper** [comment]
Nice :+1: 

I do not how ever think that the internal api's should be documented public, as they are not meant to be used directly.

**Comment by mucaho** [comment]
Ok, I removed the public documentation for the internal api.

**Comment by kevinsimper** [comment]
I can still se the documentation for `._attr_set` amd `._attr_get`?

If you remove the `@` params, it will just be internal documentation, so that it will not be published.

**Comment by mucaho** [comment]
The first line of the comment block indicates whether the docs will be parsed (on my machine at least). Only if it's `/**@` it will be parsed.

**Comment by mucaho** [comment]
Ok, thanks. I removed all `@`. Better be safe than sorry :+1:

**Comment by starwed** [comment]
This looks good to me, I'll go ahead and merge.

**Pull request merged**
