### PR TITLE
Memory Issues #127

### PR DESCRIPTION
**Pull request by BlackScorp**
With this small change i dont have Memory Issues on Ubuntu and Firefox 8, maybe iam Wrong can someone Test it?

### CODE REVIEW

**Comment by sorenbs** [comment]
closes #127
This seems to solve the problem on FF 11. But i find it a little concerning that the code you changed was not in the version of Crafty the bug was originally reported against :-)

I will merge and see if i can get the reporter to test it. Thank you!

**Comment by BlackScorp** [comment]
sorry about that, but iam actually not good with github didnt knew that the issue was made on another crafty version

**Comment by sorenbs** [comment]
I just meant that the problem was discovered on an older version of Crafty that did not have the part of the code that you changed, which means that the problem would have to be somewhere else, but perhaps we fixed the old problem and introduced this new one... That could explain it.

**Comment by BlackScorp** [comment]
i just think that my crafty does not crash anymore in Firefox even if i have more than 300 entities in my scene, it lags but not crashes anymore

**Comment by sorenbs** [comment]
That's great. We really should have some kind of automatic performance test that could run on each commit so we can keep track of how we are doing performance wise. It is all too easy to introduce problems like this one. I guess that will be my next  major Crafty related project.

**Pull request merged**
