### PR TITLE
Updated license.txt, demo and Gravity

### PR DESCRIPTION
**Pull request by pengyu**
fixed license.txt format to unix and removed crafty.js and crafty-min.js

### CODE REVIEW

**Comment by sorenbs** [comment]
There is a merge conflict in build.php. Could you try to fix it again? I think i managed to merge the rest.

**Comment by pengyu** [comment]
I'm not sure how to check the conflict. The following command doesn't show me anything. Would you please let me know what command I should use to see the conflict and resolve the conflict?

~/dvcs_src/craftyjs1/Crafty$ git merge upstream/master
Already up-to-date.  
~/dvcs_src/craftyjs1/Crafty$ git remote show 
origin
upstream
~/dvcs_src/craftyjs1/Crafty$ git remote show upstream
- remote upstream
  Fetch URL: https://github.com/louisstow/Crafty.git
  Push  URL: https://github.com/louisstow/Crafty.git
  HEAD branch: master
  Remote branches:
    Leo       tracked
    dev       tracked
    louisstow tracked
    master    tracked
    mpetrovic tracked
    sorenbs   tracked
    vector    tracked
  Local ref configured for 'git push':
    master pushes to master (local out of date)

**Comment by sorenbs** [comment]
To be honest, merge conflicts always confuses me, so what i do is i remove my local copy of the file, then do a git pull to get the github version, and the i manually make all my changes again.

**Comment by pengyu** [comment]
Could you show me what you see about the merge conflicts?

**Comment by harrislapiroff** [comment]
Peng, try this and you will see the conflicts:

```
git remote add louis https://github.com/louisstow/Crafty.git # this will add louis's repository as one that you can fetch from
git fetch louis # this will fetch all the data in louis's repository for you to play with
git merge louis/master # this will attempt to merge louis's master with yours
```

And you should see the conflicts. You'll also be able to browse the files now and see where git has marked the conflicts in the files.

**Comment by harrislapiroff** [comment]
Oh, I see you already have louis as upstream. Well, follow the latter two commands, but with upstream instead of louis.

**Comment by pengyu** [comment]
OK. I merged them. There are a few glitches. But I think it should be OK.

Merging is really a headache. Could anybody try to pull ASAP before it becomes too late? If my previous pull request was handled on time, there would not be too much headache like this.

**Comment by harrislapiroff** [comment]
There are some things we can do to make merging easier. I'm going to send an email to the whole list about some of the project changes that can be made, but as an individual developer this will help:

Create a separate branch for each change to the code you're working on which is not related to the other changes—that way you can create separate pull requests for each change, most of which will not run into conflicts. This also means that if the core developers only like _some_ of your changes, but not all of them, it's possible for them to pick and choose which changes to merge.

**Comment by pengyu** [comment]
I'm wondering how you handle multiple branches practically.

Suppose I'm editing file A, which leads to changes to file Z.

Now I need to change file B, as you suggested, I can either clone the central repository again, then make changes. But unfornately, I just realize that there should be some changes in Z as well. To make the thing worst, exactly the same part of Z should be changed.

This practice will lead to extra burden to the developers.

Also, how to clone multiple copies of the central repository seems. Do I need to fork multiple times in github?

**Comment by harrislapiroff** [comment]
It's a rare case that the same part of file Z will have to be changed. More commonly, things will Just Work. Merge conflicts are the largest burden to developers because they require poring over someone else's code and determining what is important. This model actually reduces merge conflicts.

I assure you that this is the industry standard model. Easy branch-and-merge is the feature that made Git popular—not using it is like buying a car and using it for sitting in.

Read more here: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by harrislapiroff** [comment]
Correction: it _should_ be a rare case that the same lines in Z should have to be changed, assuming your code is well-structured. If you have to change the code in two different ways in the same place, how would you possibly be able to handle  that even without branching?

**Comment by pengyu** [comment]
Thanks for the article. Since article does not directly address the environment of github and Crafty. I just clarifty my understanding of this article in the context of github and Crafty.

~/dvcs_src/craftyjs1/Crafty/src$ git remote show  origin
- remote origin
  Fetch URL: git@github.com:pengyu/Crafty.git
  Push  URL: git@github.com:pengyu/Crafty.git
  HEAD branch: master
  Remote branches:
    Leo       tracked
    dev       tracked
    louisstow tracked
    master    tracked
    mpetrovic tracked
    sorenbs   tracked
    vector    tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)

Is 'dev' here is essentialy what is referred as 'develop' in the article?

Since I'm not sure, let's use master instead. The procedure that I imagine is this.
1. fork louisstow/Crafty in github and I get pengyu / Crafty
2. Create a new branch for task1
        git checkout -b task1
   Add code and commit.
        git commit -a
   Go back to the master branch
        git checkout master
3. Repeat 2 to add new tasks task2, task3, etc.
4. Submit pull request.

Is it what you suggesting? Is it an extra burden for the person who processes the pull request to merge all these tasks?

**Comment by harrislapiroff** [comment]
Yes, that's roughly correct.

Crafty doesn't currently use the process outlined in the article (which is part of the suggestions email I just sent to the Crafty list), so the branches don't correspond to the ones outlined in the master. Here is how I did my pull request to Crafty:
1. fork louisstow/Crafty to get lapilofu/Crafty
2. `git clone <path_to_my_github_fork>` Obviously not necessarily if I have already cloned it.
3. `git checkout -b scene-uninit`
4. Make all the changes and commits I need to implement my feature until it is stable.
5. `git push origin scene-uninit` this pushes my branch to my own github fork lapilofu/Crafty:scene-uninit
6. Go to GitHub and make a pull request from lapilofu/Crafty:scene-uninit to louisstow/Crafty:master

If I want to start working on another feature while waiting for my feature to be merged, I follow these steps:
1. `git checkout master` This switches me back to the master branch, before my previous feature was implemented
2. Follow steps 3-6 above.

Once my pull request is completed, I update my master branch and usually clean up by deleting the feature branch:
1. `git checkout master`
2. `git pull louis master`
3. `git branch -d scene-uninit` This will throw an error if the branch has not yet been merged into master.
4. `git push origin :scene-uninit` This weirdly arcane syntax deletes the branch from my GitHub repository at lapilofu/Crafty:scene-uninit

It's actually easier for the person who processes the pull requests, because even if they have to process more of them, it's obvious what feature each pull request adds, so it's easy to decide whether a pull request is harmless or not. Large commit count pull requests can hide broken or malicious code buried in the hundreds of lines changed.

In a perfect world, most of these merges would also be seamless, but that's not possible with the current state of the Crafty repository, which I have addressed on the email list.

**Pull request closed without merging**
