### PR TITLE
Catch the case when accessing localStorage throws a security exception

### PR DESCRIPTION
**Pull request by starwed**
Hopefully fixes issue #989.

I had to require Crafty here for the logging functionality.

### CODE REVIEW

**Comment by mucaho** [comment]
Looks good, except for possible complications caused by requiring:
Requiring the `core` module is fine in the browser (as there is only one Crafty instance at any given time), but not that straightforward in node (as there can be multiple Crafty instances running on the server).

Remember, we always delete the cache and require a "fresh" instance of all required modules in node.
Now, in this case it's fine, as we "refreshed" the `core` module before (see [crafty_headless#L4](https://github.com/craftyjs/Crafty/blob/0.7.0/src/crafty_headless.js#L4)). If some day in the future (for w/e reason) the `storage` module gets required before the `core` module, we have a problem.

Is there a "safer" way to get access to the logging feature?

**Comment by starwed** [comment]
> Is there a "safer" way to get access to the logging feature?

We could pull in the logging feature as a separate module, the same way storage is contstructed.

**Comment by mucaho** [comment]
> We could pull in the logging feature as a separate module, the same way storage is contstructed.

Sure, I don't quite follow but sounds good :)

**Comment by starwed** [comment]
> If some day in the future (for w/e reason) the storage module gets required before the core module, we have a problem.

I think it's probably ok for now to simply insist that core is required first, and merge this PR.

I believe we decided in the original discussion that the long term fix would be to make the various modules return functions that accept the `Crafty` object, thus sidestepping the issue of caching completely.

**Comment by mucaho** [comment]
Yes, it's ok. I completely forgot we use this exact code in other src files :)

**Pull request merged**
