### PR TITLE
unselectable text should have the default arrow cursor, not text cursor, on mouse-over

### PR DESCRIPTION
**Pull request by sbyrnes321**

### CODE REVIEW

**Comment by starwed** [comment]
Makes sense.  (There's no way to reverse unselectable, right?)

**Comment by kevinsimper** [comment]
@starwed What do you mean? There is nothing to reverse the unselectable method.

**Comment by starwed** [comment]
Heh, just a typo.  (Should have been "no way to"...)

**Comment by sbyrnes321** [comment]
Correct, there is no way to reverse unselectable. I doubt anyone would want to do that. If someone requests it, it's obviously an easy feature to add.

**Pull request merged**
