### PR TITLE
Fix numerous small documentation issues

### PR DESCRIPTION
**Pull request by starwed**
This PR does two main things
- Update the doc generator and viewer to handle new tags (`@warning`, `@note`) and cross-page anchor references
- Fixes tons of small issues I found while auditing our docs as part of the 0.7.0 release.  This includes typos, malformed syntax, missing parameters, incorrect return types, convoluted phrasing, and pretty much anything else that jumped out at me!

I deliberately skipped auditing 
- the new Motion & co., since I think those are still in a bit of flux.
- The math.matrix methods, since they seem to be using a jsdoc style we haven't ever supported.  That'll require a separate PR to straighten up, one way or the other

There's a parallel PR that adds these new capabilities to the craftyjs repo.

### CODE REVIEW

**Comment by kevinsimper** [comment]
Looks good!

We should add documentation generation to travis! Wouldn't that be possible to test as well?

**Comment by starwed** [comment]
> We should add documentation generation to travis! Wouldn't that be possible to test as well?

There are some simple things I could add to the build scripts that would be good to check.  Not sure if there are any good tests to apply to the final json file in isolation.

**Comment by kevinsimper** [comment]
Would those things be including if there is any parsing error or that the api can not be generated correct?

**Comment by starwed** [comment]
> Would those things be including if there is any parsing error or that the api can not be generated correct?

Kind of... a couple of obvious things to check for are 
- unknown tags, like if someone added a `@stability` tag to the docs without updating the generator
- Pages with no description at the top, or blocks which don't specify any category or page they belong to

We could also have a small sample input, and check that the emitted json has the correct properties.

**Pull request merged**
