### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dobnarr**
Fix for Twoway jumping bug.  Think I've got it right this time.  Thanks for the help.

### CODE REVIEW

**Comment by mpetrovic** [comment]
This won't solve the problem you're describing. When jump is explicitly set to 0, !jump will return true.

**Comment by dobnarr** [comment]
I screwed it up worse than that - there's no "this._jump"
I'll redo it.

**Comment by sbyrnes321** [comment]
If you want to test whether the argument jump is missing, just do:

if (jump === undefined) {...}

Don't forget that third equals sign ;-)

It behaves exactly like you expect and the code is extremely easy to read and understand.

**Comment by dobnarr** [comment]
OK, I did it a different way (arguments.length < 2) and resubmitted.  If you all prefer the undefined, I can do it that way instead.  So we can close this request - it's not correct.  The other one should be good.

**Comment by louisstow** [comment]
This has been fixed in another PR

**Pull request closed without merging**
