### PR TITLE
Add WebDriver tests

### LINKED ISSUE #950: Regression tests for visuals / display / graphics
So we added a lot of graphics features and don't have a way to test them currently.
We could remedy this by introducing a new set of testing facilities - visual based regression tests.

**How does it work?**
Basically you have a tool which takes screenshots of web pages (or specific elements of the page), saves those that you approved as a baseline and then each time you run the tests it checks if the new screenshots it takes match the baseline screenshots within a certain error margin.

**How could we integrate it into our existing workflow?**
Preliminary research has shown two potential candidates: [Gemini](https://github.com/gemini-testing/gemini) and [WebdriverIO](http://webdriver.io/).
WebdriverIO appealed more to me from my first impressions, so I will document the proposed process with that tool a bit here:
- there is a [webdriver-grunt](http://webdriver.io/guide/plugins/grunt-webdriver.html) task which we can use to run our tests
- the tests are actually run by a WebdriverIO plugin, namely [WebdriverCSS](http://webdriver.io/guide/plugins/webdrivercss.html); you tell it the `url`, which `HTMLElement` and whether to record baseline screenshots or test against them; tests can pass / fail just like in `QUnit`
- the cool thing is these tests can be run locally in a `phantomjs` browser, but also on different browsers on the Sauce Labs server (see #927). That means we get instant feedback if all[1] of Crafty's features run on all browsers we intend to support!
- there is a [grunt-css-test](https://www.npmjs.com/package/grunt-css-test) node module that could speed up the process; also see [grunt-sauce-driver](https://www.npmjs.com/package/grunt-sauce-driver) to manually run CSS tests

**What has to change if we want to proceed with this?**
Start making tests for `DOM`, `Canvas`, `WebGL`, `Viewport`, etc.. . Look at the webpages generated by those tests and record them as a baseline if they look as expected.

Footnote [1]: All features for which we wrote tests.

### PR DESCRIPTION
**Pull request by mucaho**
Explanation moved to [Webdriver test wiki](https://github.com/craftyjs/Crafty/wiki/Webdriver-tests).
## Miscellaneous
- This PR adds example test templates, not all tests covering every functionality, some tests will come in next PR. Additional tests can always be added over time.
- fixes #950
- streamlines Gruntfile

What do you think? This should give us much needed confidence when doing changes to graphics stuff.

### CODE REVIEW

**Comment by mucaho** [comment]
Ok, updated the documentation above.
I'm pretty satisfied with the current capabilities for now (after waging battles with the differences in each browser's test capabilities).
@starwed Do you have some comments?

**Comment by starwed** [comment]
Thanks for taking the time to not just implement this, but also thoroughly explain it!

Reading through your comments it sounds good to me.  Just to check my understanding: this particular PR implements the general framework as well as two specific DOM tests?

One theoretical possibility would be to compare DOM, Canvas, and WebGL rendering of the same scene against the same screenshot.  I have a [quasi-complicated scene](http://ludonomicon.com/crafty/triple-render.html) I've been using to check a variety of functionality in the three renderers simultaneously.  (It uses all the transformations, animation, and transparency, as well as Image, Sprite, and Color entities.)

**Comment by mucaho** [comment]
Yes, this PR implements general framework + some example tests (they can be DOM, Canvas, WebGL, doesn't matter).

> One theoretical possibility would be to compare DOM, Canvas, and WebGL rendering of the same scene against the same screenshot.

Yep, you can do that by stuffing all 3 rendering stripes into the same test (as you did in your example scene), and then calling `assertResemble(bounds)` for each of these stripes' bounds.
I have deliberately removed the need to specify URLs & paths inside the tests, but the available commands can be extended to accept test page urls and screenshot file paths, if you want.

> I have a quasi-complicated scene I've been using to check a variety of functionality in the three renderers simultaneously

This is golden! Have to shrink it a bit, but can then be included as a test as explained above. I will also need to split the animation into discrete steps, as we can only compare screenshots and not videos.

**Comment by mucaho** [comment]
Merging then, more tests incoming

**Pull request merged**
