### PR TITLE
Add Travis CI status image

### PR DESCRIPTION
**Pull request by potomak**
Waiting for #540...

### CODE REVIEW

**Comment by starwed** [comment]
Should this specify the develop branch, ala `[Build Status](https://travis-ci.org/craftyjs/Crafty)`?

**Comment by bayleedev** [comment]
@starwed  why not put one for `master` and `develop` with labels?

**Comment by potomak** [comment]
@starwed I agree, update is on the way.

**Comment by starwed** [comment]
@blainesch  If the release branch ever fails the automated tests, we've done something horrifically wrong.  :)

**Pull request merged**
