### PR TITLE
Add enable and disable multiway methods to allow more flexible control

### PR DESCRIPTION
**Pull request by pengyu**

### CODE REVIEW

**Comment by pengyu** [comment]
I've added the changes. Please take a look and pull it if there is no problem.

**Comment by BlackScorp** [comment]
since Multiway is a component, why just not addComponent, removeComponent("MultiWay") ?

**Comment by harrislapiroff** [comment]
I'll try this out and merge it soon. It looks good from here though.

**Comment by pengyu** [comment]
You can use add and removeComponent. But you will have to call the following function whenever you add the component back, which is inconvenient.

.multiway(1, {UP_ARROW: -90, DOWN_ARROW: 90, RIGHT_ARROW: 0, LEFT_ARROW: 180})

**Comment by pengyu** [comment]
There has been a few days since I submitted the pull request. Could anybody pull it? Thanks!

**Comment by BlackScorp** [comment]
no, you can call the multiway function in init function so it will be called everytime if the component is added.

Crafty.c("EnableMultiway",{
init:function(){
this.requires("Multiway").multiway(1,{UP_ARROW: -90, DOWN_ARROW: 90, RIGHT_ARROW: 0, LEFT_ARROW: 180});
}
});

var test = Crafty.e("2D,Canvas,Somethink");
test.addComponent("EnableMultiway"); mulitway function was called

**Comment by sorenbs** [comment]
Even though the add/remove component paradigm is quite powerful i think it would be worth it to add the enable-/disable-control functions for use in simple cases.

**Comment by sorenbs** [comment]
merged into develop

**Pull request closed without merging**
