### PR TITLE
added simple executable example

### PR DESCRIPTION
**Pull request by mucaho**
added the example from the front page to be quickly accessible after building crafty.js

just an idea :)

### CODE REVIEW

**Comment by starwed** [comment]
We actually did have some demos included in Crafty previously; louis removed them without commenting as to why.

I always found them useful to check if any obvious functionality was broken, so we might want to include something similar again?

**Comment by mucaho** [comment]
> I always found them useful to check if any obvious functionality was broken, so we might want to include something similar again?

Agreed. 
Perhaps it was cumbersome to update the examples according to the api changes every time?

**Comment by mucaho** [comment]
There is a [demo repository](https://github.com/craftyjs/demos). Could we put them in there (e.g. labeled as developer demos)?

**Comment by starwed** [comment]
@mucaho  Yeah, if you like go ahead and put anything you like there.  :)

**Comment by mucaho** [comment]
Ok thanks, did it

**Pull request closed without merging**
