### PR TITLE
Delete trailing spaces.

### PR DESCRIPTION
**Pull request by pawurb**
How about cleaning all the trailing spaces in the project ?

### CODE REVIEW

**Comment by starwed** [comment]
Hmm, this sort of PR tends to not play well with others; changing so many files at once causes merge conflicts all over the place.

Is there a standard git technique for handling formatting changes like this?  Something that minimizes the pain?

**Comment by starwed** [comment]
[This SO post](http://stackoverflow.com/questions/9776527/git-merging-without-whitespace-conflicts) describes the exact use case we'd want: how to deal with a patch that strips trailing spaces.

**Comment by pawurb** [comment]
The way I understand it is that after merging my PR you will have to use '-Xignore-space-change' flag to avoid conflicts when merging stuff in the future. It is up to you if this if an acceptable price for getting rid of the trailing spaces.

**Comment by starwed** [comment]
Reminder: If we merge this, we should also tell jshint to warn about [trailing spaces](http://www.jshint.com/docs/options/#trailing) in the future.

**Comment by potomak** [comment]
Related: we could also introduce JSBeautifier (maybe in the grunt `check` task).
It could be used to get a consistent style between all the code base.

Example: http://flippinawesome.org/2013/12/02/eliminating-code-smell-with-grunt/

**Comment by starwed** [comment]
I merged this against the current develop branch, fixed a couple of new white space issues that had come up, and opened a new PR #673

**Pull request closed without merging**
