### PR TITLE
Radzikowski

### PR DESCRIPTION
**Pull request by radzikowski**
change name of owner in README to better git clone, change homepage in package.json.
Correct image position - https://github.com/craftyjs/Crafty/issues/158

### CODE REVIEW

**Comment by mpetrovic** [comment]
Could you reroll this so only your changes are included? As it stands now, I don't know what I should be looking at and the request can't be merged automatically.

**Comment by radzikowski** [comment]
Please fix crafty develop branch. It should be newest as he could be. All changes should be merge to develop branch and then to master branch.
Today i dont have time to corrects my pull request, in next days i will fix that, but please fix develop branch.

**Comment by mpetrovic** [comment]
Ok, its fixed. Develop is now up to date. 

We need to make sure it stays up to date, and we only do work on it. This is something I'm guilty of as well.

**Comment by ahilles107** [comment]
You must clear this PR and address to develop branch. I will close this PR.

**Pull request closed without merging**
