### PR TITLE
Fixing some odd behaviour in isometric, and adding iso tests.

### PR DESCRIPTION
**Pull request by ericathegreat**
When I was writing some tests for isometric, I noticed that px2pos and pos2px were not actually reversing each others' actions. I've adjusted that behaviour (such that px2pos(pos2px(a,b)) == (a,b)  now).

### CODE REVIEW

**Comment by ericathegreat** [comment]
Is there anything I can explain further for these changes? Would you prefer me to split the unit tests for the unchanged functionality into a separate pull request?

**Comment by kevinsimper** [comment]
No, i will look at it later today :)

**Comment by starwed** [comment]
In fact, I think it's _good_ to have the unit tests as part of the same pull request.  I wanted to give it a proper test before landing, since I'm not very familiar with how the isometric code works, which led to me putting it off.  Sorry the PR ended up hanging for a while!

**Comment by starwed** [comment]
Ok, looks fine to me. There was a merge conflict due to the jslinting fixes, but since this was such a small patch to the actual code, that was really easy to do handle manually.

**Comment by ericathegreat** [comment]
That's great, thank you! I didn't mean to hurry you along, I just wanted to make sure that _I_ hadn't done something wrong which might have been a blocker.

**Pull request merged**
