### PR TITLE
Fixes bug with text component for Canvas not being redrawn

### PR DESCRIPTION
**Pull request by kcaze**

### CODE REVIEW

**Comment by starwed** [comment]
This removes the ability to set a font size in something other than pixels, which we should allow if it is possible.

Getting the height of the text can also be more complicated than just getting the font size in any case.  Glyphs with descenders can hang below that distance, if I understand how font sizes work.

Aside: if, as in this PR, we switch how `fillText` is called, we might be able to get rid of the save/restore of the context, which would slightly help performance.

**Comment by kcaze** [comment]
I don't think there's really a good way of measuring the height of text. The simplest method (although ugly) would probably be the Matt Palmerlee's answer here: http://stackoverflow.com/questions/1134586/how-can-you-find-the-height-of-text-on-an-html-canvas.

Also, can this issue and the other one be merged somehow?

**Comment by starwed** [comment]
Creating a canvas element and measuring the text every time it changes would have way too big a performance impact!

I'm sure we can [estimate the height](http://reeddesign.co.uk/test/points-pixels.html) for several different types of units without resorting to anything so drastic.  :)

**Comment by kcaze** [comment]
As you mentioned earlier though, getting the height isn't as simple as the font size, since glyphs can descend arbitrarily low below the baseline (http://stackoverflow.com/questions/5718299/font-size-what-can-i-be-sure-of).

Also, I'm not creating a canvas element each time, I'm just creating a span. I'm not sure if this really has a significant impact on performance, but if it does, an alternative could be to create a single span to be used for measuring text height and position it off screen.

**Comment by starwed** [comment]
@kcaze Ah, sorry, somehow misread your code!  I think creating and destroying hundreds of spans per second would probably still be bad for performance, though.

I think the best solution would be to, by default, estimate the height based on the font size, but to also allow the user to override this by calling a `setHeight(height)` method.  Without arguments it would attempt to directly measure the height of the text using the technique you suggest.  (Or maybe with some special argument, with no arguments reverting to the default height?)

**Comment by kcaze** [comment]
That seems like a reasonable solution. Should the estimated height be based on the page you linked (<a href= "http://reeddesign.co.uk/test/points-pixels.html">http://reeddesign.co.uk/test/points-pixels.htm</a>l)?

A bit of leeway should be given though so that the estimated height is slightly greater than what's listed on that site.

**Comment by kevinsimper** [comment]
@starwed Do you still think that what you mention is the best solution. If yes, i will be glad to submit a pull request on that.

**Comment by starwed** [comment]
I had some trouble figuring out the best heuristic to use.  Probably best to be conservative with that?  We just  need something that works the majority of the time with common fonts, and is manually adjustable to account for outliers like international scripts.

**Comment by starwed** [comment]
Here's a sample function we could use to determine the pixel size from the font-size string.  I haven't in any way tested it, just presenting an approach we could use:

``` javascript
    // takes a CSS font-size string and gets the height of the resulting font in px
var getFontHeight = (function(){
        // regex for grabbing the first string of letters
    var re = /\b(.+?)\b)/;
    // From the CSS spec.  "em" and "ex" are undefined on a canvas.
    var multipliers = {
        "px":1,
        "pt": 4/3,
        "pc": 16,
        "cm": 96/2.54,
        "mm": 96/25.4,
        "in": 96,
        "em": undefined, 
        "ex": undefined
    };
    var fudge = 1.1;
    return function (font){
        var number = parseFloat(font);  
        var match = re.exec(font);
        var unit = match[1];
        if (multipliers[unit] !== undefined)
            return Math.ceil(number * fudge * multipliers[unit]);
        else
            return Math.ceil(number * fudge);
    }
})();
```

**Comment by toastino** [comment]
Hi! Has there been made any further progress on this issue? Because i've experienced the same behavior. Using kcaze's attempt on solving this problem, i noticed the following behavior: It fixes the problem illustrated in the fiddle in https://github.com/craftyjs/Crafty/issues/498 jet there still seems to be a problem with the redrawing of larger fonts. Here http://jsfiddle.net/Lg3Bx/1/ is a test similar to the old one but this crops the redrawn text strangely.(crafty compiled from kcaze changes) So the calculated width seems to be off by a bit as well.

**Comment by starwed** [comment]
@toastino  For now I would suggest just using DOM text.  I'll start working on a patch for Canvas text, but I think no matter what, the DOM approach will always have advantages.

**Comment by starwed** [comment]
Ok, got something working.  Modified fiddle [here](http://jsfiddle.net/Lg3Bx/5/).

Crafty was adjusting the width of text _after_ drawing it.

**Comment by starwed** [comment]
Closing this due to #620.

**Comment by toastino** [comment]
@starwed Ahh ok. I was working on a fix myself! That saved me a lot of time, thank you!

**Pull request closed without merging**
